language: node_js
node_js:
  - 0.12
  - 4
  - 4.3.2
  - 6
  - 7
env: CXX=g++-4.8
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-4.8
script: npm test && npm run bench
branches:
  only: master
matrix:
  include:
  - node_js: 6
    script: set -e; if [ -n "$SAUCE_USERNAME" ]; then travis_wait npm run zuul; sleep 3; fi
  - node_js: 6
    script: npm run coverage-ci
